name: mv

on:
  schedule:
    - cron: '31 10 * * *'
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  mv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout public repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Specify the Python version you need
  
    - name: Run Python script
      run: |
        pwd
        pip install requests bs4
        pip freeze
        python fra.py
      env:
          bot_token: ${{ secrets.bot_token }}
          chat_id: ${{ secrets.chat_id }}

          

